# Habilita el servidor en modo standalone
listen=YES
# Deshabilita IPv6
listen_ipv6=NO

# Prohíbe el login anónimo
anonymous_enable=NO
# Permite el login de usuarios locales (los del sistema, como 'ftpuser')
local_enable=YES

# Permite que los usuarios puedan escribir (subir archivos)
write_enable=YES

# "Enjaula" a los usuarios en su directorio /home
# No podrán ver el resto del sistema de archivos
chroot_local_user=YES
# Permite que la "jaula" (el home) sea escribible (necesario para chroot)
allow_writeable_chroot=YES

# Esencial para que FTP funcione detrás de firewalls/NAT (como en Docker)
pasv_enable=YES
# Rango de puertos que definimos en el Dockerfile y docker-compose
pasv_min_port=21100
pasv_max_port=21110

# Especifica que los mensajes de login y bienvenida se muestren
dirmessage_enable=YES
# Registra las transferencias
xferlog_enable=YES
# Usa el formato de log estándar
xferlog_std_format=YES

# Mantiene la conexión activa
connect_from_port_20=YES
